name: 'Maven Setup'
description: 'Setup for Java Maven Project'
inputs:
  java-version:
    description: 'The Java version to set up. Takes a whole or semver Java version.'
    default: '8'
  distribution:
    description: 'Java distribution.'
    default: 'adopt'
outputs:
  java-version:
    description: 'Actual version of the java environment that has been installed'
    value: ${{ steps.setup-java.outputs.version }}
  distribution:
    description: "Distribution of Java that has been installed"
    value: ${{ steps.setup-java.outputs.distribution }}
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - id: setup-java
      uses: actions/setup-java@v3
      with:
        java-version: '${{ inputs.java-version }}'
        distribution: '${{ inputs.distribution }}'
    - name: Generate settings.xml for Maven Builds
      uses: whelk-io/maven-settings-xml-action@v21
      with:
        servers: >
          [
            {
              "id": "github",
              "username": "${env.GITHUB_ACTOR}",
              "password": "${env.GITHUB_TOKEN}"
            },
            {
              "id": "github-owner",
              "username": "${env.GITHUB_ACTOR}",
              "password": "${env.GITHUB_TOKEN}"
            }
          ]
        repositories: >
          [
            {
              "id": "github",
              "url": "https://maven.pkg.github.com/${env.GITHUB_ACTOR}/*"
            },
            {
              "id": "github-owner",
              "url": "https://maven.pkg.github.com/${{ github.repository_owner }}/*"
            }
          ]
