name: 'Setup Maven Action'
description: 'Setup for Java Maven Project'
inputs:
  fetch-depth:
    description: 'Number of commits to fetch. 0 indicates all history for all branches and tags.'
    default: 1
  java-version:
    description: 'The Java version to set up. Takes a whole or semver Java version.'
    default: '8'
  distribution:
    description: 'Java distribution.'
    default: 'adopt'
  token:
    description: 'Personal access token (PAT) used to fetch the repository.'
    default: ${{ github.token }}
  gpg-private-key:
    description: 'GPG private key to import. Default is empty string.'
  gpg-passphrase:
    description: 'Environment variable name for the GPG private key passphrase. Default is $GPG_PASSPHRASE.'
    default: 'GPG_PASSPHRASE'
outputs:
  java-version:
    description: 'Actual version of the java environment that has been installed'
    value: ${{ steps.setup-java.outputs.version }}
  distribution:
    description: "Distribution of Java that has been installed"
    value: ${{ steps.setup-java.outputs.distribution }}
  java-home:
    description: "Path to where the java environment has been installed (same as $JAVA_HOME)"
    value: ${{ steps.setup-java.outputs.path}}
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      with:
        token: '${{ inputs.token }}'
        fetch-depth: ${{ inputs.fetch-depth }}
    - id: setup-java
      uses: actions/setup-java@v3
      with:
        java-version: '${{ inputs.java-version }}'
        distribution: '${{ inputs.distribution }}'
        gpg-private-key: '${{ inputs.gpg-private-key }}'
        gpg-passphrase: '${{ inputs.gpg-passphrase }}'
        cache: 'maven'
    - uses: whelk-io/maven-settings-xml-action@v21
      with:
        servers: >
          [
            {
              "id": "github",
              "username": "${env.GITHUB_ACTOR}",
              "password": "${{ inputs.token }}"
            },
            {
              "id": "github-actor",
              "username": "${env.GITHUB_ACTOR}",
              "password": "${{ inputs.token }}"
            }
          ]
        repositories: >
          [
            {
              "id": "github",
              "url": "https://maven.pkg.github.com/${env.GITHUB_REPOSITORY_OWNER}/*"
            },
            {
              "id": "github-actor",
              "url": "https://maven.pkg.github.com/${env.GITHUB_ACTOR}/*"
            }
          ]
