name: 'Setup Maven Action'
description: 'Setup for Java Maven Project'
inputs:
  fetch-depth:
    description: 'Number of commits to fetch. 0 indicates all history for all branches and tags. Default is 1'
    default: 1
  java-version:
    description: 'The Java version to set up. Takes a whole or semver Java version. Default is 8'
    default: '8'
  distribution:
    description: 'Java distribution. Default is adopt.'
    default: 'adopt'
  gpg-private-key:
    description: 'GPG private key to import. Default is empty string.'
  gpg-passphrase:
    description: 'Environment variable name for the GPG private key passphrase. Default is $GPG_PASSPHRASE.'
    default: 'GPG_PASSPHRASE'
  cache-strategy:
    description: 'Cache Strategy for Maven Repository. Select from [normal, fashion, restore]. Default is normal.'
    default: 'normal'
outputs:
  java-version:
    description: 'Actual version of the java environment that has been installed'
    value: ${{ steps.setup-java.outputs.version }}
  distribution:
    description: "Distribution of Java that has been installed"
    value: ${{ steps.setup-java.outputs.distribution }}
  java-home:
    description: "Path to where the java environment has been installed (same as $JAVA_HOME)"
    value: ${{ steps.setup-java.outputs.path }}
  cache-hit:
    description: 'A boolean value to indicate an exact match was found for the primary key'
    value: ${{ steps.cache-maven-normal.outputs.cache-hit }}
  cache-matched-key:
    description: 'Key of the cache that was restored'
    value: ${{ steps.cache-maven-restore.outputs.cache-matched-key }}
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
    - id: setup-java
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}
        gpg-private-key: ${{ inputs.gpg-private-key }}
        gpg-passphrase: ${{ inputs.gpg-passphrase }}
    - id: cache-maven-normal
      if: inputs.cache-strategy == 'normal'
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
    - id: cache-maven-fashion
      if: inputs.cache-strategy == 'fashion'
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ github.run_id }}-${{ github.job }}
        restore-keys: ${{ runner.os }}-maven-
    - id: cache-maven-restore
      if: inputs.cache-strategy == 'restore'
      uses: actions/cache/restore@v3
      with:
        path: ${{ github.workspace }}/.m2/repository
        key: ${{ runner.os }}-maven-${{ github.run_id }}-${{ github.job }}
        restore-keys: ${{ runner.os }}-maven-
    - name: Add default Configuration Options for the mvn command line
      shell: bash
      run: |
        [ -d .mvn ] || mkdir .mvn
        [ -f .mvn/maven.config ] || echo -e "--batch-mode\n--errors\n--fail-at-end\n--update-snapshots\n--show-version" >.mvn/maven.config
        [ -f .mvn/maven.config.additional ] && cat .mvn/maven.config.additional >>.mvn/maven.config
        cat .mvn/maven.config
        mvn -v
    - if: inputs.cache-strategy == 'restore'
      uses: dbstar-org/maven-settings-appender@v1
      with:
        local: ${{ github.workspace }}/.m2/repository
    - uses: dbstar-org/maven-settings-appender@v1
      with:
        profiles: |-
          <profile>
            <id>github</id>
            <repositories>
              <repository>
                <id>github</id>
                <url>https://maven.pkg.github.com/${{ github.repository_owner }}/*</url>
              </repository>
            </repositories>
          </profile>
        active-profiles: |-
          <activeProfile>github</activeProfile>
    - uses: dbstar-org/maven-settings-appender@v1
      if: github.repository_owner != github.actor
      with:
        servers: |-
          <server>
            <id>github-actor</id>
            <username>${{ github.actor }}</username>
            <password>${env.GITHUB_TOKEN}</password>
          </server>
        profiles: |-
          <profile>
            <id>github-actor</id>
            <repositories>
              <repository>
                <id>github-actor</id>
                <url>https://maven.pkg.github.com/${{ github.actor }}/*</url>
              </repository>
            </repositories>
          </profile>
        active-profiles: |-
          <activeProfile>github-actor</activeProfile>
    - uses: dbstar-org/maven-settings-appender@v1
      if: github.repository_owner != 'dbstar-org'
      with:
        servers: |-
          <server>
            <id>github-dbstar-org</id>
            <username>${{ github.actor }}</username>
            <password>${env.GITHUB_TOKEN}</password>
          </server>
        profiles: |-
          <profile>
            <id>github-dbstar-org</id>
            <repositories>
              <repository>
                <id>github-dbstar-org</id>
                <url>https://maven.pkg.github.com/dbstar-org/*</url>
              </repository>
            </repositories>
          </profile>
        active-profiles: |-
          <activeProfile>github-dbstar-org</activeProfile>
    - uses: dbstar-org/maven-settings-appender@v1
      with:
        servers: |-
          <server>
            <id>ossrh</id>
            <username>${env.OSS_USERNAME}</username>
            <password>${env.OSS_PASSWORD}</password>
          </server>
